### ISSUE TITLE
panic in operator e2e

### ISSUE THREAD

**Issue by sjenning** [openshift/machine-api-operator#138]
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_machine-api-operator/137/pull-ci-openshift-machine-api-operator-master-e2e-aws-operator/73/build-log.txt
```
I1126 21:49:42.191957    2157 main.go:79] RUN: ExpectAllMachinesLinkedToANode
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xeb6226]

goroutine 1 [running]:
main.(*testConfig).ExpectAllMachinesLinkedToANode(0xc4202ee0c0, 0x1, 0x1)
    /go/src/github.com/openshift/machine-api-operator/test/e2e/operator_expectations.go:124 +0x416
main.runSuite(0x0, 0x0)
    /go/src/github.com/openshift/machine-api-operator/test/e2e/main.go:80 +0x4fc
main.main()
    /go/src/github.com/openshift/machine-api-operator/test/e2e/main.go:44 +0x27
exit status 2
make: *** [test-e2e] Error 1
2018/11/26 21:49:43 Container test in pod e2e-aws-operator failed, exit code 2, reason Error
```
`NodeRef` is nil for the machine

**Comment by sjenning** [comment]
fixed by #140
